"""Core modeling modules for the Ancestry FH MMM."""

from .approval import ModelApproval, ApprovalMismatchError, require_matching_approval
from .fingerprint import fingerprint_dataframe, fingerprint_model_spec, fingerprint_posterior
from .schema import ModelSpec, DEFAULT_SEGMENTS
from .transformations import (
    geometric_adstock,
    geometric_adstock_matrix,
    hill_function,
    hill_function_scaled,
    log_transform,
    inverse_log_transform,
    pt_geometric_adstock,
    pt_geometric_adstock_matrix,
    pt_hill_function,
)
from .models import (
    build_loglog_model,
    build_lift_model,
    fit_model,
    compute_model_diagnostics,
)
from .hierarchical_model import build_fh_hierarchical_model, FHModelMeta
from .predict import (
    FHPosteriorParams,
    extract_posterior_params,
    predict_mu,
    adstock_saturate_frame,
    lag_frame,
    steady_state_segment_response,
)
from .diagnostics import (
    compute_scorecard,
    in_sample_fit,
    posterior_predictive_coverage,
    curve_plausibility_checks,
    expanding_window_backtest,
)
from .curve_bank import (
    CurveBankEntry,
    CalibrationRecord,
    make_entry,
    save_entry,
    load_all_entries,
    entries_to_dataframe,
    compare_to_test,
    record_calibration,
    load_all_calibrations,
    calibrations_to_dataframe,
)
from .attribution import (
    compute_shapley_contributions,
    segment_channel_summary,
    total_fh_contribution,
    contribution_waterfall,
    compute_shapley_values,
    decompose_sales,
    calculate_roi,
)
from .optimization import (
    SpendConstraint,
    evaluate_scenario,
    optimize_scenario,
    scenario_to_dict,
    scenario_from_dict,
    compare_scenarios,
    calculate_marginal_roi_loglog,
    optimize_budget_marginal_roi,
    calculate_expected_lift,
)
from .persistence import (
    export_project,
    import_project,
    export_excel_summary,
    UnsafeZipEntryError,
    reconstruct_model_state,
    verify_imported_approval,
)
from .market_config import (
    MarketDescriptors,
    MarketCurrency,
    MarketProfile,
    ChannelMediaUnitConfig,
    MarketSpecConfig,
    UNIT_TYPE_SUGGESTIONS,
    COST_BASIS_SUGGESTIONS,
    market_data_quality_status,
)
from .simulation import (
    MarketSimSpec,
    ChannelSimSpec,
    SimulationGroundTruth,
    SimulationResult,
    default_markets,
    default_channels,
    simulate_market_specific_panel,
)

__all__ = [
    "ModelApproval",
    "ApprovalMismatchError",
    "require_matching_approval",
    "fingerprint_dataframe",
    "fingerprint_model_spec",
    "fingerprint_posterior",
    "ModelSpec",
    "DEFAULT_SEGMENTS",
    "geometric_adstock",
    "geometric_adstock_matrix",
    "hill_function",
    "hill_function_scaled",
    "log_transform",
    "inverse_log_transform",
    "pt_geometric_adstock",
    "pt_geometric_adstock_matrix",
    "pt_hill_function",
    "build_loglog_model",
    "build_lift_model",
    "fit_model",
    "compute_model_diagnostics",
    "build_fh_hierarchical_model",
    "FHModelMeta",
    "FHPosteriorParams",
    "extract_posterior_params",
    "predict_mu",
    "adstock_saturate_frame",
    "lag_frame",
    "steady_state_segment_response",
    "compute_scorecard",
    "in_sample_fit",
    "posterior_predictive_coverage",
    "curve_plausibility_checks",
    "expanding_window_backtest",
    "CurveBankEntry",
    "CalibrationRecord",
    "make_entry",
    "save_entry",
    "load_all_entries",
    "entries_to_dataframe",
    "compare_to_test",
    "record_calibration",
    "load_all_calibrations",
    "calibrations_to_dataframe",
    "compute_shapley_contributions",
    "segment_channel_summary",
    "total_fh_contribution",
    "contribution_waterfall",
    "compute_shapley_values",
    "decompose_sales",
    "calculate_roi",
    "SpendConstraint",
    "evaluate_scenario",
    "optimize_scenario",
    "scenario_to_dict",
    "scenario_from_dict",
    "compare_scenarios",
    "calculate_marginal_roi_loglog",
    "optimize_budget_marginal_roi",
    "calculate_expected_lift",
    "export_project",
    "import_project",
    "export_excel_summary",
    "UnsafeZipEntryError",
    "reconstruct_model_state",
    "verify_imported_approval",
    "MarketDescriptors",
    "MarketCurrency",
    "MarketProfile",
    "ChannelMediaUnitConfig",
    "MarketSpecConfig",
    "UNIT_TYPE_SUGGESTIONS",
    "COST_BASIS_SUGGESTIONS",
    "market_data_quality_status",
    "MarketSimSpec",
    "ChannelSimSpec",
    "SimulationGroundTruth",
    "SimulationResult",
    "default_markets",
    "default_channels",
    "simulate_market_specific_panel",
]
