[theme]
primaryColor = "#117FA6"
backgroundColor = "#F6F3F0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202923"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
